function writeHeader() {
  document.write('<a class="company-logo" href="http://www.parallels.com">Parallels</a><div class="header-area"><h1><a class="product-logo" href="http://www.parallels.com/products/panel/intro" title="Parallels Plesk Panel">Parallels Plesk Panel</a></h1><span class="header-text"><a class="top-copyright" href="http://www.parallels.com">&copy; 1999-2011, Parallels<br />All rights reserved</a>');
  document.write('</span></div>');
}
function writeFooter() {
  document.write('<p class="description">This page was generated by <a href="http://www.parallels.com/products/panel/intro">Parallels Plesk Panel</a></p>');
}
function writeCopyFlag() {
  document.write('<script type="text/javascript" src="http://' + (location.hostname.indexOf(':')>=0?'['+location.hostname+']':location.hostname) + ':8880/javascript/promo-flags.js.php"></' + 'script>\n');
}
