<BR><BR><table width="880" border="0" cellspacing="0" cellpadding="0"><tr><td width="10px"></td><td colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Question No : </font><BR><BR></td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3">Which of the following is NOT a component of Facilities Management?</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width=" ">&nbsp;</td><td width="7%"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 1 </font></td><td><font face="Arial,sans-serif" size="3">Shipping and Receiving</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 2 </font></td><td><font face="Arial,sans-serif" size="3"> Physical Access Control</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 3 </font></td><td><font face="Arial,sans-serif" size="3"> Procurement advice</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 4 </font></td><td><font face="Arial,sans-serif" size="3">Equipment Hosting</font></td></tr><td colspan="3">&nbsp;</td></tr><tr><td>&nbsp;</td</tr><tr><td width=" ">&nbsp;</td><td width=" " colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Correct Choice : 3</font></td> </tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Justification : </font><BR><BR></td></tr><tr><td width=" ">&nbsp;</td><td valign="top" colspan="2"><font face="Arial,sans-serif" size="3">The main components of Facilities Management are as follows-
•	Building Management
•	Equipment Hosting
•	Power Management
•	Environmental conditioning and alert systems
•	Safety
•	Physical Access Control
•	Shipping and Receiving
•	Involvement in Contract Management of the various suppliers
•	Maintenance
<BR><BR></td></tr><tr><td colspan="3">&nbsp;</font></td></tr>