<!--#include virtual="/metatags/PMI_PDU_metatag.html"-->
<!--#include virtual="/includes/headermeta.asp"-->
<!--#include virtual="/includes/innerwhyusbanner.html"-->
<!-- Body Starts -->

<div>
  <table width="930" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td height="235" align="left" valign="top" bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="8">
          <tr>
            <td width="2%" >&nbsp;</td>
            <td width="25%">&nbsp;</td>
            <td width="73%" class="breadcrumb"><a href="/index.asp" title="Home">Home</a> &raquo; WHY US &raquo; PMI Approved PDUs </td>
          </tr>
          <tr>
            <!--#include virtual="/includes/innerLeftMenu.asp"-->
            <td width="73%" rowspan="4" background="/images/back/left_line.jpg" class="general-body"><div style="margin-top:-12px; width:97%;">
                <!-- Content Start From Here-->
                <h1 class="PageTitle">PMI APPROVED PDUS</h1>
                <p><span class="SubHeader">PMI Approved PDUs:</span> ITILstudy provides 27 PMI approved PDUs for ITIL Intermediate  courses - these are valid PDUs for continuing education requirements of PMPs, to maintain their PMP Certification Status.</p>
				
				
                <p><span class="SubHeader">ITILstudy, an Edusys' brand, is amongst the select group of ATO's accredited by APM Group, UK. ITILstudy specialises in conducting quality classroom training programs to prepare delegates for ITIL Foundation certification.</p>
              
                 <p>Associated with PMstudy - PMstudy is a brand of VMEdu, Inc., which is  a leading Project Management Institute (PMI)<sup>&reg;</sup> Approved Global Registered Education Provider, specializing in providing quality education to prepare students for Project Management Professional (PMP)<sup>&reg;</sup> and Certified Associate in Project Management (CAPM)<sup>&reg;</sup> Certification Exams.</p>
             
                <p>The PDUs provided by ITILstudy can be generated by the students after completing the ITILstudy Classroom Program. On the final day of the program the students will be given the option to download their PDUs certificate.</p>
              <% If Session("CountryOrigin") = "India" Then%>
              <p> <span class="SubHeader">Please Note:</span></p>
             <p>27 PDUs would be provided to those students' who enroll for the ITILstudy ITIL Foundation classroom course.</p>
			 <% End IF %>
                
                <!-- Content End From Here-->
              </div></td>
          </tr>
        </table></td>
    </tr>
  </table>
</div>
<!-- Body Ends -->
<!--#include virtual="/includes/footer.html"-->
