<BR><BR><table width="880" border="0" cellspacing="0" cellpadding="0"><tr><td width="10px"></td><td colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Question No: 6</font><BR><BR></td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><p>You have recently been appointed as continual service improvement (CSI)  manager for your company. You have had many years experience with implementing  ITIL best practices across other companies. Within the IT organization, many of  the ITIL processes have already been implemented and the company has now  decided to mature its practices by adopting the ITIL service lifecycle. CSI has  been selected as one of the first stages of their service lifecycle to  implement.</p></font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Question:</b> As the CSI  manager you first establish a baseline, as this is an important starting point  for highlighting improvement and to determine if a process needs to be  improved. It is essential to collect this data even if the integrity of the  initial baseline data is in question.<br>
  Which one of  the following options is the BEST next step to help identify which processes to  improve first?</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width=" ">&nbsp;</td><td width="7%"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 1 </font></td><td><font face="Arial,sans-serif" size="3">Work with IT and business management to validate the data for completeness and accuracy so that informed improvement decisions may be made based on the data. Internal benchmarking data, if available, can also demonstrate where improvements have taken place within the organization so far. This will be useful in establishing the relative priorities within each of the processes before the improvement programme commences.</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 2 </font></td><td><font face="Arial,sans-serif" size="3"> Interview business personnel to validate the data for completeness and accuracy so that informed improvement decisions may be made based on the data. Getting a business perspective from the customers and end-users will give you a much better idea when identifying which processes to improve first, so that the right improvement opportunities are realized.</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 3 </font></td><td><font face="Arial,sans-serif" size="3"> External benchmarking should be used as the management technique to improve performance.
Benchmarking is the only way to open an organization to new methods, ideas and tools in order to improve its effectiveness. Benchmarking will reduce the resistance to change by demonstrating other methods of solving problems than the one currently employed, and demonstrating that these are far better as they are being used successfully by other companies.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Choice 4 </font></td><td><font face="Arial,sans-serif" size="3">Interview IT personnel, to validate the data for completeness and accuracy so that informed improvement decisions may be made based on the data. You will bear this in mind when you establish the relative priorities within each of the processes before the improvement programme commences, and after you have established and confirmed a second baseline.</font></td></tr><td colspan="3">&nbsp;</td></tr><tr><td>&nbsp;</td</tr><tr><td width=" ">&nbsp;</td><td width=" " colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Correct Choice : A</font></td> </tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font style="font-family:Arial, Helvetica, sans-serif; color:#2F95D3; font-size: 13px; font-weight: bold; font-style: normal;">Justification : </font><BR><BR></td></tr><tr><td width=" ">&nbsp;</td><td valign="top" colspan="2"><font face="Arial,sans-serif" size="3"><table border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td width="154" valign="top"><p><strong><em>QUESTION</em></strong></p></td>
    <td width="45" valign="top"><p><strong>CHOICE</strong></p></td>
    <td width="402" valign="top"><p align="center"><strong>RATIONALE</strong></p></td>
  </tr>
  <tr>
    <td width="154" valign="top"><p><strong><em>MOST CORRECT (5)</em></strong></p></td>
    <td width="45" valign="top"><p>A</p></td>
    <td width="402" valign="top"><p>In the provided scenario, utilizing both benchmarking data and    baseline data (recognizing that the integrity of the data may be in question)    will firmly establish the right processes to address first. In addition,    where there have been positive changes in performance over time, they may    give the opportunity for weaker processes to be prioritized first. Finally,    this answer recognizes the value of qualitative research from both customer    and peer feedback. </p></td>
  </tr>
  <tr>
    <td width="154" valign="top"><p><strong><em>SECOND BEST (3)</em></strong></p></td>
    <td width="45" valign="top"><p>B</p></td>
    <td width="402" valign="top"><p>This answer recognizes the need to understand baseline data and has    also recognized the strength of qualitative research from customer feedback.<br>
      However, use of benchmarking data is still important to establish    either how far the company has moved on its improvement journey already, or how    the company compares with other companies in the sector. </p></td>
  </tr>
  <tr>
    <td width="154" valign="top"><p><strong><em>THIRD BEST (1)</em></strong></p></td>
    <td width="45" valign="top"><p>D</p></td>
    <td width="402" valign="top"><p>This answer recognizes the need to understand baseline data and has    also recognized the strength of qualitative research from peer feedback.    However, use of benchmarking data is still important to establish either how    far the company has moved on its improvement journey already, or how the    company compares with other companies in the sector. This answer does not,    however, find out what is important to the business, focusing only on IT    personnel.<br>
      Additionally waiting for a second baseline will cause undue delays and    may jeopardize the enthusiasm. </p></td>
  </tr>
  <tr>
    <td width="154" valign="top"><p><strong><em>DISTRACTER (0)</em></strong></p></td>
    <td width="45" valign="top"><p>C</p></td>
    <td width="402" valign="top"><p>This answer recognizes the need to understand benchmarking data.    However, it fails to recognize that baseline data is equally important in    establishing the importance of data trends. Additionally, benchmarking is not    the only way to get things done and, contrary to the answer, the staff is not    resistant to the change but rather is enthusiastic about it. Finally, this    answer does not attempt to perform qualitative research with either the    customer or peers. </p></td>
  </tr>
</table>
<p> </p>
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr>