<!--#include virtual="/ITIL-OSA-Sample1/sample1Ques/validOSA.asp"--><BR><BR><form  method="post" action="./index.asp"><div class="overflowTest"><table width="880" border="0" cellspacing="0" cellpadding="0"><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Scenario:</b> A computer  games retailer has had a very aggressive business growth pattern. This growth  has been achieved by opening many new outlets and most significantly, by buying  three other companies in the computer games market. It has also expanded its  head office premises where a number of administrative and support services will  be centralized.
<p>The IT systems  that the original company used were basic and were not managed or supported by clearly  defined processes. The three new companies are similar, although one  specializes in internet sales which have now become a significant part of  overall business revenue.</p>
<p>The IT  Director (an employee for many years) has decided that the quality of IT  service delivery is essential in ensuring IT services support the Business’s  ambitious plans for further growth. The internet sales Company has some  expertise in ITIL and the IT Director is now convinced that ITIL is a trusted  framework which will enable the company to achieve its goals.</p>
An external  assessment has concluded that the current Incident Management process is  lacking maturity and that a good starting point would be to review the Service  Desk function and ensure commonality across the organization.</br>
</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Question:</b> Which one of the following sequences of activities BEST describes what this organization can accomplish in the next four months in support of the business goals?</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width=" ">&nbsp;</td><td width="7%"><font face="Arial,sans-serif" size="3">1 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=A></font></td><td><font face="Arial,sans-serif" size="3"><ul>
  <li>Centralize the Service Desk in the Head Office and  train staff</li>
  <li>Implement a new Service Desk tool enabling Incidents  to be appropriately recorded</li>
  <li>Define the Incident Management process </li>
</ul>
<p>Although the  emphasis is on the Incident Management process, it is essential that Request  Fulfilment, Problem Management, Event Management and Change Management are  fully implemented at the same time, as they all have significant interfaces  into Incident Management.</p></td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">2 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=B></font></td><td><font face="Arial,sans-serif" size="3"> <ul>
  <li>Centralize the Service Desk in the Head Office</li>
  <li>Assess the Incident Management processes</li>
  <li>Define a new Incident Management process based on ITIL.</li>
</ul>
<p>Once the  process has been agreed, documented and approved, a tool can be implemented and  the staff trained to use the product. Integration with Event Management,  Request Fulfilment, Service<br>
  Level  Management and Problem Management can then be implemented so that the  interfaces can be fully utilized.</p></td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">3 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=C></font></td><td><font face="Arial,sans-serif" size="3"> <ul>
  <li>Implement a central Service Desk in the Head Office  with local Service Desks at three other locations, all utilizing the same tool.</li>
  <li>Shared information between the Service Desks via an  integrated Configuration Management System (CMS)</li>
  <li>Define the Incident Management process.</li>
</ul>
<p>Once the process  has been documented and approved, a tool can be implemented in all locations and  staff and customers trained to utilize the product as logging of Incidents will  be possible via the Internet. It is intended that the Service Desk tool and  staff will be used for several other processes so this should be planned even  if everything is not implemented immediately. Processes such as Event Management,  Request Fulfilment, Service Level Management and Problem Management will be integrated  into the tool.</p></td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">4 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=D></font></td><td><font face="Arial,sans-serif" size="3"><ul>
  <li>Centralize the Service Desk in the Head Office.</li>
  <li>Assess the Incident Management processes</li>
  <li>Revise the process based on ITIL and existing  processes, tailored to fit the four separate elements of the business.</li>
</ul>
<p>Once the  process has been agreed, documented and approved, a tool can be implemented and  the staff and customers trained to use the product as logging of Incidents will  be possible via the Internet. It is intended that the Service Desk tool and  staff will be used for other processes so this should be planned for, even if  everything is not implemented immediately. Integration with all other ITIL  processes can then be implemented so that all the interfaces can be fully  utilized.</p></td></tr><tr><td colspan="3">&nbsp;</font></td></tr>