<BR><BR><form method="post" action="./index.asp"><div class="overflowTest"><table width="880" border="0" cellspacing="0" cellpadding="0"><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Scenario:</b> <p>You are the IT  service manager for a national company. You have invited the IT senior  management team to a meeting to discuss the scope for an assessment to  establish a baseline for future comparison and improvement. This assessment is  the starting point in an attempt to identify why the various business units  within the company believe that IT is not responding to their needs, while IT  believes the opposite.</p>
During the  meeting, it becomes obvious there are differences of opinion among the various  managers concerning the scope for the assessment:</p>
<ul>
 <li> One group believes that the assessment should cover  only the service management processes</li>
 <li> Another is of the opinion that the assessment should  cover people, processes and technology</li>
 <li> The remainder believe that a full assessment covering  all aspects of IT is required.</li>
</ul>
 
Considerations  discussed to identify the correct scope for the assessment include:
<ul>
 <li>The majority of the IT infrastructure is less than two  years old and is causing no apparent issues</li>
 <li>There is limited co-operation between the various IT  groups</li>
 <li>Nearly three quarters of the IT staff have been with  the company for more than 15 years.</li>
</ul>
Some of the managers  (who have achieved ITIL Foundation certification) believe that they are the  appropriate ones to conduct the assessment; however, others feel this is  neither necessary nor relevant to the exercise.<br/></font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Question:</b> Which one of the following options BEST represents the scope of the assessment for the company at this time?
</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width=" ">&nbsp;</td><td width="7%"><font face="Arial,sans-serif" size="3">1 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=A></font></td><td><font face="Arial,sans-serif" size="3">The scope of the assessment should cover only the processes. The technology does not need to be included as it is less than two years old and is not causing any issues.
Since most IT employees have been with the company for more than 15 years, it is understandable that there will be some relationship and co-operation issues.
In order to view whether the processes are aligned with ITIL, the assessment should look at both process governance and management information.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">2 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=B></font></td><td><font face="Arial,sans-serif" size="3"> The scope of the assessment should cover people, process, and technology.
Although the technology is less than two years old, incidents may arise, changes are happening, and the business is complaining about ITs responsiveness. This could be an indication that processes and people are misaligned as the business and IT do not have a balanced view on how they integrate. The assessment should look at process governance, technology issues, and management information.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">3 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=C></font></td><td><font face="Arial,sans-serif" size="3"> The scope should only cover people and processes. The technology can be excluded since it is less than two years old and is not causing any issues. It would, however, be appropriate to allow only those managers who have achieved the ITIL Foundation certificate to participate in the process assessment, as they will have an appreciation of all the processes and will, therefore, have a greater understanding on the standards required.</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">4 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=D></font></td><td><font face="Arial,sans-serif" size="3"><p>The assessment  needs to be a full assessment and should therefore cover people, process, and  technology, including acceptance.<br>
  Knowledge of  ITIL is not a prerequisite for IT staff performing the assessment, as long as  they have the appropriate understanding of the assessment process. The  assessment should identify any cultural issues (which can have an impact on the  success of an improvement program), the progress of business and IT  integration, process governance and management information. </p></td></tr><tr><td colspan="3">&nbsp;</font></td></tr>