<BR><BR><form method="post" action="./index.asp"><div class="overflowTest"><table width="880" border="0" cellspacing="0" cellpadding="0"><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Scenario:</b> A nuclear  power company is faced with various levels of legislative compliance. This  requires the company to have a robust business continuity plan that must be regularly  tested and updated if any issues are identified.
<p>The power  generation products of the company must be managed very carefully as  disruptions in production or quality can pose risks to public safety. The  business continuity (BC) manager is therefore concerned about the ongoing  assurance that risks are managed appropriately, to ensure that the company can  continue operating without disruption to its critical business services which  were identified in the business impact analysis.</p>
<p>The IT service  continuity (ITSC) manager has been working in the field of ITSC for the last 15  years.<br>
  Within this  company, the processes and procedures are all clearly defined, organized, and maintained.  When BC or ITSC testing is carried out, it is normal for the tests to work well  and for the staff involved to be able to perform their role. The BC manager and  ITSC manager are not only old friends, but also work well together.</p></font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width="10px"></td><td colspan="2"><font face="Arial,sans-serif" size="3"><b>Question:</b> Which one of the following options BEST represents your contribution as the continual service improvement (CSI) manager to business continuity management (BCM) and IT service continuity management (ITSCM) in this company?</font><BR><BR></td></tr><tr><td colspan="3">&nbsp;</td></tr><tr><td width=" ">&nbsp;</td><td width="7%"><font face="Arial,sans-serif" size="3">1 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=A></font></td><td><font face="Arial,sans-serif" size="3">CSI can complement these activities and therefore help to deliver business benefit.
CSI can assess the results of any risk management activities and review BCM or ITSCM test results to identify potential service improvements (such as risk mitigation measures). This will also serve to enhance the ongoing assurance that the critical business services are covered in the event of a disaster.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">2 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=B></font></td><td><font face="Arial,sans-serif" size="3"> You should assess the relationship between the ITSC manager and the BC manager, as personal relationships could have a detrimental effect on the quality of work. You should also check whether risk management activities are conducted during the design phase of the ITIL service lifecycle, as the managers should not wait until the critical business services are live before reviewing them.</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">3 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=C></font></td><td><font face="Arial,sans-serif" size="3"> You can contribute most effectively by participating in the annual ITSCM process review that the 
ITSC manager has developed, and providing feedback on any improvement efforts identified. You should produce a complementary report that identifies any errors, omissions, incompleteness and which indicates where you believe there are further improvement opportunities for BCM. This will assure the business that it is adequately covered in the event of a disaster.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr><tr><td width=" ">&nbsp;</td><td width=" "><font face="Arial,sans-serif" size="3">4 &nbsp;&nbsp; <INPUT TYPE="radio" NAME="SelectedChoice" VALUE=D></font></td><td><font face="Arial,sans-serif" size="3">You need to assess the current procedures that the ITSC manager has already developed and is using. Also, you can positively contribute by providing baselines and benchmarking information in order to identify potential gaps and omissions in the plans, in association with industry best practice. 
The ITSC manager will then decide if the information provided by CSI is relevant or not.
</td></tr><tr><td colspan="3">&nbsp;</font></td></tr>