<!--#include virtual="/includes/header.asp"-->
<!--#include virtual="/includes/innerwhyusbanner.html"-->
<!--#include virtual="/includes/connection.asp"-->
<!--#include virtual="/metatags/chapterTest_metatag.html"-->
<!-- Body Starts -->
<SCRIPT LANGUAGE="JavaScript">
<!-- Begin
function popUp(URL) {
day = new Date();
id = day.getTime();
eval("page" + id + " = window.open(URL, '" + id + "', 'toolbars=0,left=1,top=1,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=600,height=500');");
}
// End -->
</script>

<div>
<table width="930" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
  
  <td height="235" align="left" valign="top" bgcolor="#FFFFFF">
  
  <table width="100%" border="0" cellspacing="0" cellpadding="8">
    <tr>
      <td width="2%" class="Header">&nbsp;</td>
      <td width="25%" class="PageTitle">&nbsp;</td>
      <td width="73%" class="breadcrumb"><a href="/index.asp" title="Home">Home</a> &raquo; ITIL &raquo; Understanding ITIL Foundation sample paper</td>
    </tr>
    <tr>
      <!--#include virtual="/includes/innerLeftMenu.asp"-->
      <td width="73%" rowspan="4" background="/images/back/left_line.jpg" class="general-body"><span class="PageTitle">FULL LENGTH APMG SAMPLE PAPER FOR ITIL FOUNDATION EXAM PREP</span><br />
        <br>
        <div> APMG sample paper is the closest you can get to the final ITIL Foundation certification exam.
Prepared by certified ITIL experts, APMG sample paper provides all the features of a full length ITIL Foundation certification exam.<br>
          <br>
         Each simulated test consists of 40 questions to be answered within 1 hour. Like in the actual
ITIL Foundation exam, test contains 40 random questions generated by the system. The
objective of this test is to help you understand how well -prepared you are to appear for the
final ITIL Foundation exam. Our detailed analysis of the result will help you to identify
your focus areas so that you can take further steps to focus more attention on them.<br>
          <br>
          <span class="SubHeader">Some of the Features of APMG sample paper:</span><br>
           <ul>
                  <li><span class="SubHeader"><strong>While taking the test:</strong></span></li>
                  <p><b>Click  image to enlarge</b></p>
                  <p><a href="/practice/ITIL/examBig.png" target="_blank"><img src="/practice/ITIL/Mocktest.png" width="288px" height="148px" border="0" style="border:1px #CCCCCC solid;"/></a></p>
                  <ul>
                    <li> You should select one answer from the four  available options.</li>
                    <li><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Previous&nbsp;&nbsp;</span> Previous   Button allows you to navigate to the previous question.</li>
                    <li><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Next&nbsp;&nbsp;</span> Next   Button allows you to navigate to the next question.
                      <p>You can also click <strong>'Next'</strong> button if you want to skip a difficult question and would like to go to the next question. You can view the list of such skipped questions when you click <strong>'View All Answers'</strong> button, which is explained below.</p>
                    </li>
                    <li><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Mark&nbsp;&nbsp;</span> Button allows you to mark a question.  You will mark a question if you are not sure of the answer and would like to come back to review it later. You can mark a question with or without selecting the  answer. When you click the Mark button, it turns into <span style="background-color:#000066; color:#FF3300; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Marked&nbsp;&nbsp;</span>. You will unmark a question when you come back, review, and decide upon the answer. To unmark, click the <strong>'Marked'</strong> button again. You can view the list of such marked questions when you click <strong>'View All Answers'</strong> button, which is explained below.</li>
                    <li><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;View All Answers&nbsp;&nbsp;</span> Button allows you to navigate to the 'View All Answers' page where you can view all your answers, marked questions and skipped questions.  You can now go back to the marked questions and the skipped questions to review and select answers for them. You can view all answers page,
                      <ol>
                        <li>At the end of the test</li>
                        <li>At any point during the test to know how you are performing in terms of time already spent and time remaining so that you can decide to go back to either marked questions or skipped questions to review and answer.</li>
                      </ol>
                      <p><b>Click  image to enlarge</b></p>
                      <p><a href="/practice/viewallanswersBig.html" target="_blank"><img src="/images/buttons/viewallanswers_snapshot_small.jpg" width="288px" height="149px" style="border:1px #CCCCCC solid;"/></a></p>
                      <p><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Show Marked&nbsp;&nbsp;</span> button helps you navigate through the marked questions, if any. Once you click here, it will take you to the first marked question for your review. Once you review and answer this question, you click <strong>'Next'</strong> button to go to the next marked question and so on. After answering each  marked question, you can either unmark it by clicking the <strong>'Marked'</strong> button or keep it marked if you want  to review it again.Anytime during the process, if you want to see your  answers page,  click '<strong>View All Answers'</strong> button again.</p>
                      <p><span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;Show Skipped&nbsp;&nbsp;</span> button helps you navigate through the skipped  questions, if any. Once you click here, it will take you to the first skipped  question for your review. Once you review and answer this question, you click <strong>'Next'</strong> button to go the next skipped question and  so on.</p>
                    </li>
                    <li> <span style="background-color:#000066; color:#FFFFFF; font-size:13px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;End Exam&nbsp;&nbsp;</span> button helps you to navigate to the test evaluation  page. &nbsp;You should click <strong>'End Exam'</strong> button,  only after you finish answering all the questions, reviewing all marked and  skipped questions and when you want to submit the test for evaluation.
                      <p><span class="Note"> Note: </span>You will not be able to come back to answer any  question once you click <strong>'End Exam'</strong> button.</p>
                    </li>
                  </ul>
                  <li><span class="SubHeader"><strong>Test Evaluation:</strong> </span></li>
                  <p><b>Click  image to enlarge</b></p>
                  <p><a href="/practice/ITIL/evaluation-l.png" target="_blank"><img src="/practice/ITIL/evaluation.png" width="288px" height="149px" style="border:1px #CCCCCC solid;"/></a></p>
                  <p>Once you click the <strong>'End Exam'</strong> button, you will be directed to 'Evaluate All Answers' page. In this page, you will find three sections in which all the details of the score that enable you to plan your future course of study are explained. They are as follows -</p>
                  <ol>
                    <li><strong>Detailed Score:</strong> Here you find answer status to all the questions you have
answered. You also find correct answers to all the questions, justification for each answer, and time taken to answer each question.
                     
                    </li>
                    <li><strong>Overall Test Score:</strong> This will give you the total number of correct answers,
your overall score as a percentage, the number of marked questions, the
number of correct answers to the marked questions, and total time spent in
answering the questions.</li>
                   
                  </ol>
                  <li><span class="SubHeader"><strong>Continuing a test from where you left off</strong></span></li>
                  <ul>
                    <li>Before taking any test, PROJstudy provides you with a <span class="general-bodyBold">Unique Test Number</span>. In case you
have to discontinue a test (for any reason e.g. problems with your ISP, your
computer crashing or just if you want to take a break), the Test Number will
allow you to continue taking the test from where you left off.<br />
                      <br />
                      <strong>How to continue a test, or evaluate your answers in a test you had taken earlier?</strong> </li>
                    <ol>
                      <li>Please log in to PROJstudy.com using your UserID and Password. Please click on "Member Login" on top menubar to go to your member login page. </li>
                      <li>After logging in, please click on "APMG sample paper" on the top menubar; this will show you the practice tests you have access to. </li>
                      <li>Please select your Unique Test Number from the drop down box and click on "Continue with Test". You can now continue the test from where you left off. </li>
                      <li>After answering all the questions, click &quot;View All Answers&quot; button.</li>
                      <li>You can now evaluate your answers to see how well you performed in the test.
                        <p><span class="Note">Note:</span>You can view your answers <strong>"only for 1 week"</strong>. </p>
                      </li>
                    </ol>
                  </ul>
                 
                  
                </ul>
         
        </div>
    </div>
    
    </td>
    
    </tr>
    
  </table>
  </td>
  
  </tr>
  
</table>
</div>
<!-- Body Ends -->
<!--#include virtual="/includes/footer.html"-->
